### ISSUE TITLE
When I start the program via python this is what is shows 

### ISSUE THREAD

**Issue by jason7861** [KrashKrash/nonce-recovery-attack#1]
Traceback (most recent call last):
  File "C:\Usersl\nonce-recovery-attack\start.py", line 61, in <module>
    result = nonce_recovery(r, s, z, k_guess, public_key)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Usersl\nonce-recovery-attack\start.py", line 8, in nonce_recovery
    public_key = VerifyingKey.from_string(public_key_bytes, curve=SECP256k1).to_string()[:32]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\ecdsa\keys.py", line 275, in from_string
    point = PointJacobi.from_bytes(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\ecdsa\ellipticcurve.py", line 575, in from_bytes
    coord_x, coord_y = super(PointJacobi, cls).from_bytes(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\ecdsa\ellipticcurve.py", line 409, in from_bytes
    raise MalformedPointError(
ecdsa.errors.MalformedPointError: Length of string does not match lengths of any of the enabled (uncompressed, raw, compressed, hybrid) encodings of the curve.

**Comment by KrashKrash** [comment]
Hey man..sorry I just read your comment. 
I never got the notifications. I'm updating the code and I will get back to you on this issue.

**Comment by greenpp88** [comment]
Is there any update?

**Comment by KrashKrash** [comment]
> Is there any update?
yeah. its updated. sorry for the 1 year 1 month delay...

**Comment by KrashKrash** [comment]
> Traceback (most recent call last): File "C:\Usersl\nonce-recovery-attack\start.py", line 61, in result = nonce_recovery(r, s, z, k_guess, public_key) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Usersl\nonce-recovery-attack\start.py", line 8, in nonce_recovery public_key = VerifyingKey.from_string(public_key_bytes, curve=SECP256k1).to_string()[:32] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\ecdsa\keys.py", line 275, in from_string point = PointJacobi.from_bytes( ^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\ecdsa\ellipticcurve.py", line 575, in from_bytes coord_x, coord_y = super(PointJacobi, cls).from_bytes( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\ecdsa\ellipticcurve.py", line 409, in from_bytes raise MalformedPointError( ecdsa.errors.MalformedPointError: Length of string does not match lengths of any of the enabled (uncompressed, raw, compressed, hybrid) encodings of the curve.

its updated.
